/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mc.music;

import mc.music.data.InitializerMusic;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ResourceBundle;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import mc.MediaCenter;

/**
 *
 * @author i22balur
 */
public class MusicAlbum extends javax.swing.JPanel {
    
    MusicAlbum(String name) {
        mediaMusic = new InitializerMusic();
        albumNames = mediaMusic.filterAlbumNames(name);
        mediaMusic.filterAlbums(name);
        background = new ImageIcon(Toolkit.getDefaultToolkit().getImage((getClass().getResource("/mc/wallpaper.jpg")))).getImage();
        initComponents();
        
        
        // Modify album list
        
        DefaultListModel model = new DefaultListModel();
        
        for (int i= 0; i<albumNames.length; i++) {
            model.addElement(albumNames[i]);
        }

        albumList.setModel(model);

        
        // Resize Icons
        Image backImg = ((ImageIcon)backArtist.getIcon()).getImage();
        backImg = backImg.getScaledInstance(55, 55,  java.awt.Image.SCALE_SMOOTH ) ;  
        backArtist.setIcon(new ImageIcon(backImg));
        
        // Initialize description
        albumList.setSelectedIndex(0);
        name = albumList.getModel().getElementAt(0);
        String description = mediaMusic.getAlbumDescription(name);
        //System.out.println(description);
        ImageIcon photo = mediaMusic.getAlbumPhoto(name);

        this.description.setText(description);

        Image img = ((ImageIcon)photo).getImage();
        img = img.getScaledInstance(520, 260,  java.awt.Image.SCALE_SMOOTH ) ;
        this.albumImage.setIcon(new ImageIcon(img));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backArtist = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        albumList = new javax.swing.JList<>();
        infoAlbum = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        albumImage = new javax.swing.JLabel();
        labelAlbum = new javax.swing.JLabel();

        backArtist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mc/back.png"))); // NOI18N
        backArtist.setContentAreaFilled(false);
        backArtist.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        backArtist.setPreferredSize(new java.awt.Dimension(80, 80));
        backArtist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backArtistMouseClicked(evt);
            }
        });

        albumList.setBackground(new java.awt.Color(0,0,0,175));
        albumList.setFont(new java.awt.Font("Ubuntu", 3, 21)); // NOI18N
        albumList.setForeground(new java.awt.Color(254, 254, 254));
        albumList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Cross Road", "The Circle" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        albumList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                albumListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(albumList);

        infoAlbum.setBackground(new java.awt.Color(0,0,0,175));
        infoAlbum.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        description.setBackground(java.awt.Color.darkGray);
        description.setColumns(20);
        description.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        description.setForeground(new java.awt.Color(254, 254, 254));
        description.setLineWrap(true);
        description.setRows(5);
        jScrollPane1.setViewportView(description);

        albumImage.setPreferredSize(new java.awt.Dimension(65, 43));

        javax.swing.GroupLayout infoAlbumLayout = new javax.swing.GroupLayout(infoAlbum);
        infoAlbum.setLayout(infoAlbumLayout);
        infoAlbumLayout.setHorizontalGroup(
            infoAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoAlbumLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(albumImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE))
                .addContainerGap())
        );
        infoAlbumLayout.setVerticalGroup(
            infoAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoAlbumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(albumImage, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        labelAlbum.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        labelAlbum.setForeground(new java.awt.Color(254, 254, 254));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("mc/Bundle"); // NOI18N
        labelAlbum.setText(bundle.getString("labelAlbum")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(infoAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(labelAlbum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backArtistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backArtistMouseClicked
        MediaCenter topFrame = (MediaCenter) SwingUtilities.getWindowAncestor(this);
        topFrame.getWindow().removeAll();
        if(topFrame.isMusicWeb())
            topFrame.getWindow().add(new MusicWeb(mediaMusic));
        else
            topFrame.getWindow().add(topFrame.getMusicArtists());
        topFrame.getWindow().repaint();
        topFrame.getWindow().revalidate();
    }//GEN-LAST:event_backArtistMouseClicked

    private void albumListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_albumListMouseClicked
        
        int index = albumList.locationToIndex(evt.getPoint());
        String name = albumList.getModel().getElementAt(index);
      
        if(evt.getClickCount() == 2) {          
            MediaCenter topFrame = (MediaCenter) SwingUtilities.getWindowAncestor(this);
            topFrame.getWindow().removeAll();
            topFrame.getWindow().add(new MusicSong(name));
            topFrame.getWindow().repaint();
            topFrame.getWindow().revalidate();
        }
        else {
            String description = mediaMusic.getAlbumDescription(name);
            ImageIcon photo = mediaMusic.getAlbumPhoto(name);
            this.description.setText(description);
            Image img = ((ImageIcon)photo).getImage();
            img = img.getScaledInstance(520, 260,  java.awt.Image.SCALE_SMOOTH ) ;  
            this.albumImage.setIcon(new ImageIcon(img));
        }        

    }//GEN-LAST:event_albumListMouseClicked
    
    public void paintComponent(Graphics g) {
        g.drawImage(background, 0, 0, null);
    }
    
    public void configureLanguage(ResourceBundle rb) {
        labelAlbum.setText(rb.getString("labelAlbum"));
        //System.out.println("gola");
    }
    
    // Custom variables
    Image background;
    InitializerMusic mediaMusic;
    String [] albumNames;
    // End of custom variables

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel albumImage;
    private javax.swing.JList<String> albumList;
    private javax.swing.JButton backArtist;
    private javax.swing.JTextArea description;
    private javax.swing.JPanel infoAlbum;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelAlbum;
    // End of variables declaration//GEN-END:variables
}
