/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mc;

import java.awt.PopupMenu;
import java.awt.Toolkit;
import javax.swing.JPanel;
import mc.music.MusicAlbum;
import mc.music.MusicArtist;
import mc.video.Video;

/**
 * Main class of the system
 * 
 * @author Rafael Barbudo Lunar
 */
public class MediaCenter extends javax.swing.JFrame {

    /**
     * Creates new form MediaCenter
     */
    public MediaCenter() {
                
        // Init the components
        initComponents();
        
        // Set the application icon
        setIconImage(Toolkit.getDefaultToolkit().getImage((getClass().getResource("icon.png"))));
        
        // Set the main view
        window.removeAll();
        window.add(main);
        window.repaint();
        window.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        window = new javax.swing.JPanel();
        main = new mc.Principal();
        musicArtists = new mc.music.MusicArtist();
        video = new mc.video.Video();
        musicAlbum = new mc.music.MusicAlbum();
        myImage = new mc.image.MyImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Media Center");

        window.setLayout(new java.awt.CardLayout());
        window.add(main, "card6");
        window.add(musicArtists, "card4");
        window.add(video, "card5");
        window.add(musicAlbum, "card5");
        window.add(myImage, "card6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(window, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(window, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MediaCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MediaCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MediaCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MediaCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MediaCenter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private mc.Principal main;
    private mc.music.MusicAlbum musicAlbum;
    private mc.music.MusicArtist musicArtists;
    private mc.image.MyImage myImage;
    private mc.video.Video video;
    private javax.swing.JPanel window;
    // End of variables declaration//GEN-END:variables

    public JPanel getWindow() {
        return window;
    }

    public void setWindow(JPanel window) {
        this.window = window;
    }
    
    public JPanel getMusicArtists() {
        return musicArtists;
    }
    
    public JPanel getVideo() {
        return video;
    }

    public JPanel getMain() {
        return main;
    }

    public JPanel getMusicAlbum() {
        return musicAlbum;
    }
    
    public void setMusicAlbum(MusicAlbum musicAlbum) {
        this.musicAlbum = musicAlbum;
    }
    
    public JPanel getMyImage() {
        return myImage;
    }
}
