/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mc;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import music.MusicArtist;

/**
 *
 * @author i22balur
 */
public class Principal extends javax.swing.JPanel {
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        background = new ImageIcon(Toolkit.getDefaultToolkit().getImage((getClass().getResource("wallpaper.jpg")))).getImage();
        initComponents();
        
        // Resize Icons
        Image newimg = ((ImageIcon)music.getIcon()).getImage();
        newimg = newimg.getScaledInstance(120, 120,  java.awt.Image.SCALE_SMOOTH ) ;  
        music.setIcon(new ImageIcon(newimg));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        music = new javax.swing.JButton();

        setBorder(null);
        setOpaque(false);

        music.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mc/music.png"))); // NOI18N
        music.setContentAreaFilled(false);
        music.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        music.setPreferredSize(new java.awt.Dimension(120, 120));
        music.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                musicMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                musicMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                musicMouseEntered(evt);
            }
        });
        music.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(music, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(701, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(222, Short.MAX_VALUE)
                .addComponent(music, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void musicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musicMouseClicked
        MediaCenter topFrame = (MediaCenter) SwingUtilities.getWindowAncestor(this);
        topFrame.getVentana().removeAll();
        topFrame.getVentana().add(topFrame.getMusic());
        topFrame.getVentana().repaint();
        topFrame.getVentana().revalidate();
    }//GEN-LAST:event_musicMouseClicked

    private void musicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_musicActionPerformed

    private void musicMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musicMouseEntered
        music.setBackground(Color.GREEN);
    }//GEN-LAST:event_musicMouseEntered

    private void musicMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musicMouseExited
        music.setBackground(Color.RED);
    }//GEN-LAST:event_musicMouseExited

    
    @Override
    public void paintComponent(Graphics g) {
        g.drawImage(background, 0, 0, null);
        //ImageIcon imageIcon = new ImageIcon("wallpaper.jpg"); // load the image to a imageIcon
        //Image image = imageIcon.getImage(); // transform it 
        //Image newimg = image.getScaledInstance(this.getWidth(), this.getHeight(),  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
        //imageIcon = new ImageIcon(newimg);  // transform it back  
        //jLabel1.setIcon(imageIcon);
    }

    // Variables propias
    Image background;
    // Fin variables propias
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton music;
    // End of variables declaration//GEN-END:variables
}
