/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mc;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import mc.image.MyImage;
import mc.music.MusicAlbum;
import mc.music.MusicArtist;
import mc.video.Video;

/**
 *
 * @author i22balur
 */
public class Principal extends javax.swing.JPanel {
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        
        // Set initial language
        Locale.setDefault(es);
        
        background = new ImageIcon(Toolkit.getDefaultToolkit().getImage((getClass().getResource("/mc/wallpaper.jpg")))).getImage();
        initComponents();
        
        // Resize Icons
        Image musicImg = ((ImageIcon)music.getIcon()).getImage();
        musicImg = musicImg.getScaledInstance(200, 200,  java.awt.Image.SCALE_SMOOTH ) ;  
        music.setIcon(new ImageIcon(musicImg));

        Image videoImg = ((ImageIcon)video.getIcon()).getImage();
        videoImg = videoImg.getScaledInstance(200, 200,  java.awt.Image.SCALE_SMOOTH ) ;  
        video.setIcon(new ImageIcon(videoImg)); 
        
        Image imageImg = ((ImageIcon)image.getIcon()).getImage();
        imageImg = imageImg.getScaledInstance(200, 200,  java.awt.Image.SCALE_SMOOTH ) ;  
        image.setIcon(new ImageIcon(imageImg)); 
        
        Image languageImg = ((ImageIcon)language.getIcon()).getImage();
        languageImg = languageImg.getScaledInstance(75, 75,  java.awt.Image.SCALE_SMOOTH ) ;  
        language.setIcon(new ImageIcon(languageImg)); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        music = new javax.swing.JButton();
        video = new javax.swing.JButton();
        image = new javax.swing.JButton();
        imageString = new javax.swing.JLabel();
        musicString = new javax.swing.JLabel();
        videoString = new javax.swing.JLabel();
        language = new javax.swing.JButton();
        dock = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();

        setBorder(null);
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(960, 540));

        music.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mc/music.png"))); // NOI18N
        music.setContentAreaFilled(false);
        music.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        music.setPreferredSize(new java.awt.Dimension(120, 120));
        music.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                musicMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                musicMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                musicMouseEntered(evt);
            }
        });

        video.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mc/video.png"))); // NOI18N
        video.setContentAreaFilled(false);
        video.setPreferredSize(new java.awt.Dimension(120, 120));
        video.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                videoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                videoMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                videoMouseEntered(evt);
            }
        });

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mc/image.png"))); // NOI18N
        image.setContentAreaFilled(false);
        image.setPreferredSize(new java.awt.Dimension(120, 120));
        image.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imageMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imageMouseEntered(evt);
            }
        });

        imageString.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        imageString.setForeground(new java.awt.Color(254, 254, 254));
        imageString.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("mc/Bundle"); // NOI18N
        imageString.setText(bundle.getString("Principal.imageString.text")); // NOI18N

        musicString.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        musicString.setForeground(new java.awt.Color(254, 254, 254));
        musicString.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        musicString.setText(bundle.getString("Principal.musicString.text")); // NOI18N

        videoString.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        videoString.setForeground(new java.awt.Color(254, 254, 254));
        videoString.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        videoString.setText(bundle.getString("Principal.videoString.text")); // NOI18N

        language.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mc/spanish.png"))); // NOI18N
        language.setContentAreaFilled(false);
        language.setPreferredSize(new java.awt.Dimension(60, 60));
        language.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                languageMouseClicked(evt);
            }
        });
        language.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                languageActionPerformed(evt);
            }
        });

        dock.setText(bundle.getString("Principal.dock.text")); // NOI18N

        jLabel1.setText(bundle.getString("Principal.jLabel1.text")); // NOI18N

        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel1)
                .addContainerGap(202, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(music, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(musicString, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(videoString, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imageString)
                        .addGap(127, 127, 127))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dock)
                            .addComponent(video, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78)
                        .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(language, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dock)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(video, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(music, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(musicString, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imageString, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(videoString, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(language, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void musicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musicMouseClicked
        MediaCenter topFrame = (MediaCenter) SwingUtilities.getWindowAncestor(this);
        topFrame.getWindow().removeAll();
        topFrame.getWindow().add(topFrame.getMusicArtists());
        topFrame.getWindow().repaint();
        topFrame.getWindow().revalidate();
    }//GEN-LAST:event_musicMouseClicked

    private void languageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_languageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_languageActionPerformed

    private void languageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_languageMouseClicked
                
        if (Locale.getDefault() == es) {
            Locale.setDefault(en);
            language.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mc/english.png")));
            Image languageImg = ((ImageIcon)language.getIcon()).getImage();
        }
        else {
            Locale.setDefault(es);
            language.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mc/spanish.png")));
        }
        // Change icon size
        Image languageImg = ((ImageIcon)language.getIcon()).getImage();
        languageImg = languageImg.getScaledInstance(60, 60,  java.awt.Image.SCALE_SMOOTH ) ;  
        language.setIcon(new ImageIcon(languageImg));
        
        // Change language
        ResourceBundle rb = ResourceBundle.getBundle("mc/Bundle",Locale.getDefault());      
        changeLanguage(rb);
    }//GEN-LAST:event_languageMouseClicked

    private void videoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_videoMouseClicked
        MediaCenter topFrame = (MediaCenter) SwingUtilities.getWindowAncestor(this);
        topFrame.getWindow().removeAll();
        topFrame.getWindow().add(topFrame.getVideo());
        topFrame.getWindow().repaint();
        topFrame.getWindow().revalidate();
    }//GEN-LAST:event_videoMouseClicked

    private void imageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageMouseClicked
        MediaCenter topFrame = (MediaCenter) SwingUtilities.getWindowAncestor(this);
        topFrame.getWindow().removeAll();
        topFrame.getWindow().add(topFrame.getMyImage());
        topFrame.getWindow().repaint();
        topFrame.getWindow().revalidate();
    }//GEN-LAST:event_imageMouseClicked

    private void musicMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musicMouseEntered
        // Change icon size  
        //music.setSize(180, 180);
        
        //Image musicImg = ((ImageIcon)music.getIcon()).getImage();
        //musicImg = musicImg.getScaledInstance(180, 180,  java.awt.Image.SCALE_SMOOTH ) ;  
        //music.setIcon(new ImageIcon(musicImg)); 
        
        
    }//GEN-LAST:event_musicMouseEntered

    private void musicMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musicMouseExited
        
        
        //music.setSize(120, 120);
        
        // Change icon size
        //Image musicImg = ((ImageIcon)music.getIcon()).getImage();
        //musicImg = musicImg.getScaledInstance(120, 120,  java.awt.Image.SCALE_SMOOTH ) ;  
        //music.setIcon(new ImageIcon(musicImg));      
    }//GEN-LAST:event_musicMouseExited

    private void videoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_videoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_videoMouseEntered

    private void videoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_videoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_videoMouseExited

    private void imageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_imageMouseEntered

    private void imageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_imageMouseExited

    
    @Override
    public void paintComponent(Graphics g) {
        g.drawImage(background, 0, 0, null);
    }

    public void changeLanguage (ResourceBundle rb) {
        imageString.setText(rb.getString("Principal.imageString.text"));
        videoString.setText(rb.getString("Principal.videoString.text"));
        musicString.setText(rb.getString("Principal.musicString.text"));
        
        MediaCenter topFrame = (MediaCenter) SwingUtilities.getWindowAncestor(this);
        ((Video) topFrame.getVideo()).configureLanguage(rb);
        ((MusicArtist) topFrame.getMusicArtists()).configureLanguage(rb);
        ((MyImage) topFrame.getMyImage()).configureLanguage(rb);
    }
    
    // Custom variables
    Image background;
    Locale es = new Locale("es","ES");
    Locale en = new Locale("en","GB");
    // End of custom variables
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dock;
    private javax.swing.JButton image;
    private javax.swing.JLabel imageString;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton language;
    private javax.swing.JButton music;
    private javax.swing.JLabel musicString;
    private javax.swing.JButton video;
    private javax.swing.JLabel videoString;
    // End of variables declaration//GEN-END:variables
}
