/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mc.video;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ResourceBundle;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import mc.MediaCenter;
import mc.video.data.InitializerVideo;

/**
 *
 * @author i22balur
 */
public class VideoWeb extends javax.swing.JPanel {


    public VideoWeb() 
    {     
        mediaVideo = new InitializerVideo();
        background = new ImageIcon(Toolkit.getDefaultToolkit().getImage((getClass().getResource("/mc/wallpaper.jpg")))).getImage();
        
        initComponents();       
       
        // Initialize the list
        DefaultListModel model = new DefaultListModel();
        localFilmNames = mediaVideo.filterLocalFilms();
        
        for (String localFilmName : localFilmNames)
            model.addElement(localFilmName);

        videoList.setModel(model);
        
        //model = (DefaultListModel) videoList.getModel();
        //model.addElement("Batman vs Superman");
        
        // Resize back icon
        Image backImg = ((ImageIcon)back.getIcon()).getImage();
        backImg = backImg.getScaledInstance(55, 55,  java.awt.Image.SCALE_SMOOTH ) ;  
        back.setIcon(new ImageIcon(backImg));
            
        // Initialize description of the first film        
        videoList.setSelectedIndex(0);
        String name = videoList.getModel().getElementAt(0);
        String description = mediaVideo.getVideoDescription(name);
        ImageIcon photo = mediaVideo.getVideoPhoto(name);
        this.description.setText(description);
        Image img = ((ImageIcon)photo).getImage();
        img = img.getScaledInstance(520, 260,  java.awt.Image.SCALE_SMOOTH ) ;
        this.videoImage.setIcon(new ImageIcon(img));
        
        if(mediaVideo.isLocal(name)) {         
            Image local = (new ImageIcon(getClass().getResource("/mc/hdd.png"))).getImage();
            local = local.getScaledInstance(30, 30,  java.awt.Image.SCALE_SMOOTH ) ;            
            this.isLocal.setText("Local");
            this.isLocal.setIcon(new ImageIcon(local));
        }
        else {
            Image local = (new ImageIcon(getClass().getResource("/mc/web.png"))).getImage();
            local = local.getScaledInstance(30, 30,  java.awt.Image.SCALE_SMOOTH ) ;            
            this.isLocal.setText("Web");
            this.isLocal.setIcon(new ImageIcon(local));
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        videoList = new javax.swing.JList<>();
        infoVideo = new javax.swing.JPanel();
        scrollDescription = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        videoImage = new javax.swing.JLabel();
        isLocal = new javax.swing.JLabel();
        labelFilm = new javax.swing.JLabel();

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mc/back.png"))); // NOI18N
        back.setContentAreaFilled(false);
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        back.setPreferredSize(new java.awt.Dimension(80, 80));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        videoList.setBackground(java.awt.Color.darkGray);
        videoList.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N
        videoList.setForeground(new java.awt.Color(254, 254, 254));
        videoList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Batman vs Superman", "El Señor de los anillos", "Iron Man 3" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        videoList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                videoListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(videoList);

        infoVideo.setBackground(java.awt.Color.darkGray);
        infoVideo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        scrollDescription.setBorder(new javax.swing.border.MatteBorder(null));

        description.setEditable(false);
        description.setBackground(java.awt.Color.darkGray);
        description.setColumns(20);
        description.setFont(new java.awt.Font("Ubuntu Light", 3, 18)); // NOI18N
        description.setForeground(new java.awt.Color(254, 254, 254));
        description.setLineWrap(true);
        description.setRows(5);
        description.setAutoscrolls(false);
        description.setBorder(new javax.swing.border.LineBorder(java.awt.Color.gray, 2, true));
        description.setDisabledTextColor(new java.awt.Color(254, 254, 254));
        description.setFocusable(false);
        scrollDescription.setViewportView(description);

        videoImage.setPreferredSize(new java.awt.Dimension(65, 43));

        isLocal.setBackground(java.awt.Color.darkGray);
        isLocal.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N
        isLocal.setForeground(new java.awt.Color(254, 254, 254));
        isLocal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mc/hdd.png"))); // NOI18N
        isLocal.setText("Local");

        javax.swing.GroupLayout infoVideoLayout = new javax.swing.GroupLayout(infoVideo);
        infoVideo.setLayout(infoVideoLayout);
        infoVideoLayout.setHorizontalGroup(
            infoVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoVideoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoVideoLayout.createSequentialGroup()
                        .addComponent(isLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(infoVideoLayout.createSequentialGroup()
                        .addGroup(infoVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(videoImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoVideoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(scrollDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        infoVideoLayout.setVerticalGroup(
            infoVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoVideoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(videoImage, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(isLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        labelFilm.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        labelFilm.setForeground(new java.awt.Color(254, 254, 254));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("mc/Bundle"); // NOI18N
        labelFilm.setText(bundle.getString("filmsLabel")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(infoVideo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoVideo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(labelFilm)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        MediaCenter topFrame = (MediaCenter) SwingUtilities.getWindowAncestor(this);
        topFrame.getWindow().removeAll();
        topFrame.getWindow().add(topFrame.getMain());
        topFrame.getWindow().repaint();
        topFrame.getWindow().revalidate();
    }//GEN-LAST:event_backMouseClicked

    private void videoListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_videoListMouseClicked
        int index = videoList.locationToIndex(evt.getPoint());
        String name = videoList.getModel().getElementAt(index);
        String description = mediaVideo.getVideoDescription(name);
        ImageIcon photo = mediaVideo.getVideoPhoto(name);

        this.description.setText(description);

        Image img = ((ImageIcon)photo).getImage();
        img = img.getScaledInstance(520, 260,  java.awt.Image.SCALE_SMOOTH ) ;
        this.videoImage.setIcon(new ImageIcon(img));
    }//GEN-LAST:event_videoListMouseClicked

    public void paintComponent(Graphics g) 
    {
        g.drawImage(background, 0, 0, null);
    }
    
    public void configureLanguage(ResourceBundle rb) 
    {
        labelFilm.setText(rb.getString("filmsLabel"));
    }
    
    // Custom variables
    private Image background;
    private InitializerVideo mediaVideo;
    private String [] localFilmNames;
    // End of custom variables

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextArea description;
    private javax.swing.JPanel infoVideo;
    private javax.swing.JLabel isLocal;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelFilm;
    private javax.swing.JScrollPane scrollDescription;
    private javax.swing.JLabel videoImage;
    private javax.swing.JList<String> videoList;
    // End of variables declaration//GEN-END:variables

    public JPanel getInfoVideo() 
    {
        return infoVideo;
    }
    
    public JLabel getLabelFilm() 
    {
        return labelFilm;
    }
}
