/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mc.video;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ResourceBundle;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import mc.MediaCenter;
import mc.video.data.InitializerVideo;

/**
 *
 * @author i22balur
 */
public class Video extends javax.swing.JPanel {

    /**
     * Creates new form Video
     */
    public Video() {
        
        mediaVideo = new InitializerVideo();
        background = new ImageIcon(Toolkit.getDefaultToolkit().getImage((getClass().getResource("/mc/wallpaper.jpg")))).getImage();
        
        initComponents();
        
        // Resize Icons
        Image backImg = ((ImageIcon)back.getIcon()).getImage();
        backImg = backImg.getScaledInstance(55, 55,  java.awt.Image.SCALE_SMOOTH ) ;  
        back.setIcon(new ImageIcon(backImg));
        
        
        // Initialize description
        String name = videoList.getModel().getElementAt(0);
        String description = mediaVideo.getVideoDescription(name);
        ImageIcon photo = mediaVideo.getVideoPhoto(name);

        this.description.setText(description);

        Image img = ((ImageIcon)photo).getImage();
        img = img.getScaledInstance(520, 260,  java.awt.Image.SCALE_SMOOTH ) ;
        this.videoImage.setIcon(new ImageIcon(img));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        videoList = new javax.swing.JList<>();
        infoVideo = new javax.swing.JPanel();
        scrollDescription = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        videoImage = new javax.swing.JLabel();
        labelFilm = new javax.swing.JLabel();

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mc/back.png"))); // NOI18N
        back.setContentAreaFilled(false);
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        back.setPreferredSize(new java.awt.Dimension(80, 80));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        videoList.setBackground(java.awt.Color.darkGray);
        videoList.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N
        videoList.setForeground(new java.awt.Color(254, 254, 254));
        videoList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Batman vs Superman", "El Señor de los anillos", "Iron Man 3" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        videoList.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                videoListMouseMoved(evt);
            }
        });
        jScrollPane2.setViewportView(videoList);

        infoVideo.setBackground(java.awt.Color.darkGray);
        infoVideo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        scrollDescription.setBorder(new javax.swing.border.MatteBorder(null));

        description.setEditable(false);
        description.setBackground(java.awt.Color.darkGray);
        description.setColumns(20);
        description.setFont(new java.awt.Font("Ubuntu Light", 3, 18)); // NOI18N
        description.setForeground(new java.awt.Color(254, 254, 254));
        description.setLineWrap(true);
        description.setRows(5);
        description.setAutoscrolls(false);
        description.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        description.setDisabledTextColor(new java.awt.Color(254, 254, 254));
        description.setFocusable(false);
        scrollDescription.setViewportView(description);

        videoImage.setPreferredSize(new java.awt.Dimension(65, 43));

        javax.swing.GroupLayout infoVideoLayout = new javax.swing.GroupLayout(infoVideo);
        infoVideo.setLayout(infoVideoLayout);
        infoVideoLayout.setHorizontalGroup(
            infoVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoVideoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(infoVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                    .addComponent(videoImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        infoVideoLayout.setVerticalGroup(
            infoVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoVideoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(videoImage, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        labelFilm.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        labelFilm.setForeground(new java.awt.Color(254, 254, 254));
        labelFilm.setText("Películas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(infoVideo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(infoVideo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(labelFilm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        MediaCenter topFrame = (MediaCenter) SwingUtilities.getWindowAncestor(this);
        topFrame.getWindow().removeAll();
        topFrame.getWindow().add(topFrame.getMain());
        topFrame.getWindow().repaint();
        topFrame.getWindow().revalidate();
    }//GEN-LAST:event_backMouseClicked

    private void videoListMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_videoListMouseMoved
        int index = videoList.locationToIndex(evt.getPoint());
        String name = videoList.getModel().getElementAt(index);
        String description = mediaVideo.getVideoDescription(name);
        ImageIcon photo = mediaVideo.getVideoPhoto(name);

        this.description.setText(description);

        Image img = ((ImageIcon)photo).getImage();
        img = img.getScaledInstance(520, 260,  java.awt.Image.SCALE_SMOOTH ) ;
        this.videoImage.setIcon(new ImageIcon(img));

    }//GEN-LAST:event_videoListMouseMoved

    public void paintComponent(Graphics g) {
        g.drawImage(background, 0, 0, null);
    }
    
    public void configureLanguage(ResourceBundle rb) {
        labelFilm.setText(rb.getString("Principal.language.text"));
    }
    
    // Custom variables
    Image background;
    InitializerVideo mediaVideo;
    // End of custom variables

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextArea description;
    private javax.swing.JPanel infoVideo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelFilm;
    private javax.swing.JScrollPane scrollDescription;
    private javax.swing.JLabel videoImage;
    private javax.swing.JList<String> videoList;
    // End of variables declaration//GEN-END:variables

    public JPanel getInfoVideo() {
        return infoVideo;
    }
    
    public JLabel getLabelFilm() {
        return labelFilm;
    }
}
